FROM maven:3.9-eclipse-temurin-21 AS build
WORKDIR /build
COPY pom.xml .
RUN mvn -q dependency:go-offline
COPY src ./src
RUN mvn -q package -DskipTests

FROM eclipse-temurin:21-jre-alpine
WORKDIR /app
COPY --from=build /build/target/micro-pedidos-1.0.0.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-Xmx192m", "-jar", "app.jar"]
